version: "3.3"

services:
    graphein-cpu:
        image: 'graphein-cpu:latest'
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                CUDA: cpu
                TORCH: '1.7.1'
        volumes:
            - ./:/graphein
        command: tail -f /dev/null
