version: "3.3"

services:
  graphein-gpu:
    image: 'graphein-gpu:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/graphein
    command: tail -f /dev/null
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
