version: "3.3"

services:
    graphein-cpu:
        image: 'graphein-cpu:latest'
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/graphein
        command: tail -f /dev/null
