version: "3.3"

services:
    graphein-cpu:
        image: 'graphein-cpu:latest'
        environment:
          CUDA: cpu
          TORCH: '1.7.1'
        build:
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - ./:/graphein
        command: tail -f /dev/null