name: graphein
channels:
- conda-forge
- anaconda
- bioconda
- plotly
- schrodinger
- salilab
dependencies:
- python=3.8
- biopython
- biopandas
- conda
- click
- dssp
- flake8
- interrogate
- ipympl
- isort
- jupyter
- jupyterlab
- mamba
- matplotlib
- anaconda::multipledispatch
- mypy
- networkx
- nodejs
- numpy
- pandas
- pandoc
- pip
- plotly
- pre-commit
- pydantic
- pymol
- pyyaml
- scikit-learn
- scipy
- tqdm
- versioneer
- python-wget
- xarray
- deepdiff
- click
- pip:
  - bioservices
  - biovec
  - propy3
  - pyaaisc
  - git+https://github.com/a-r-j/graphein

