name: build

on:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - "CONTRIBUTORS.md"
      - "CONTRIBUTING.md"
      - "docs/**"

  pull_request:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - "CONTRIBUTORS.md"
      - "CONTRIBUTING.md"
      - "docs/*"

jobs:
  build_cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        torch: [2.6.0, 2.7.0, 2.8.0]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: "latest"
          environment-name: test_env
          init-shell: bash
          create-args: python=${{matrix.python-version}}
          post-cleanup: "all"
      - name: Install DSSP
        run: micromamba install dssp -c salilab
      - name: Install mmseqs
        run: micromamba install -c conda-forge -c bioconda mmseqs2
      - name: Install Boost 1.7.3 (for DSSP)
        run: micromamba install -c anaconda libboost=1.73.0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install Graphein and dependencies
        run: uv sync --extra dev --extra extras --extra docs
      - name: Install PyTorch
        run: uv pip install torch==${{matrix.torch}} -f https://download.pytorch.org/whl/cpu
      - name: Install PyG
        run: uv pip install torch_geometric
      - name: Install torch-cluster
        run: uv pip install torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-${{matrix.torch}}+cpu.html
      - name: Install BLAST
        run: sudo apt install ncbi-blast+
      - name: Run unit tests and generate coverage report
        run: uv run pytest .
      - name: Test notebook execution
        run: uv run pytest --nbval-lax notebooks/ --nbval-current-env --ignore-glob="notebooks/dataloader_tutorial.ipynb" --ignore-glob="notebooks/datasets_and_dataloaders.ipynb" --ignore-glob="notebooks/foldcomp.ipynb" --ignore-glob="notebooks/grn_tutorial.ipynb"
