name: minimal_install

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "CHANGELOG.md"
      - "CONTRIBUTORS.md"
      - "CONTRIBUTING.md"

  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/*"
      - "CHANGELOG.md"
      - "CONTRIBUTORS.md"
      - "CONTRIBUTING.md"
      - "imgs/"

jobs:
  build_cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install Graphein and dependencies
        run: uv sync --extra dev --extra extras
      - name: Run unit tests and generate coverage report
        run: uv run pytest . --ignore-glob="tests/protein/tensor" --ignore="tests/ml/test_conversion.py" --ignore="tests/ml/test_torch_geometric_dataset.py"
      - name: Test notebook execution
        run: uv run pytest --nbval-lax notebooks/ --nbval-current-env --ignore-glob="notebooks/dataloader_tutorial.ipynb" --ignore-glob="notebooks/higher_order_graphs.ipynb" --ignore-glob="notebooks/protein_graph_analytics.ipynb" --ignore-glob="notebooks/subgraphing_tutorial.ipynb" --ignore-glob="notebooks/splitting_a_dataset.ipynb" --ignore-glob="notebooks/protein_tensors.ipynb" --ignore-glob="notebooks/datasets_and_dataloaders.ipynb" --ignore-glob="notebooks/foldcomp.ipynb" --ignore-glob="notebooks/creating_datasets_from_the_pdb.ipynb" --ignore-glob="notebooks/grn_tutorial.ipynb"
